baseURL = "https://productoversee.com/"
languageCode = "pt-br"
title = "Product Oversee - o portal de conteúdo para PMs com opinião"
description = "O Product Oversee é um portal de conteúdo para pessoas que constróem produtos e serviços digitais no Brasil."
theme = "productoversee-v1"
removePathAccents = true
summaryLength = 10
[markup.goldmark.renderer]
  unsafe= true
enableRobotsTXT = true
disableLiveReload = false

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[permalinks]
  posts = "/:slug"
  pages = "/:slug"

[imaging]
  quality = 65

[related]
  threshold = 100
  includeNewer = true
  toLower = false

  [[related.indices]]
  name  = "tags"
  weight = 30
  [[related.indices]]
  name  = "categories"
  weight = 40
  [[related.indices]]
  name  = "title"
  weight = 30


[params.sponsor]
  [params.sponsor.awari]
      active = false
      name = "awari"
      site = "https://awari.com.br/"
      logo = "/images/sponsors/awari@3x.webp"
      banner = "/images/sponsors/awari@3x.webp"
      paragraph_description = "Aprenda as habilidades mais requisitadas pelo mercado, receba mentoria de profissionais referência em suas áreas de atuação e conte com a ajuda de profissionais especializados para conquistar uma vaga em sua nova área."
  [params.sponsor.ituring]
      active = true
      name = "ituring"
      site = "https://ituring.com.br/analise-de-dados-para-negocios?utm_source=productoversee"
      logo = "/images/sponsors/ituring-logo.png"
      banner = "/images/sponsors/ituring-banner.png"
      paragraph_description = "O ITuring é um instituto de educação em tecnologia e negócios da era digital."
  [params.sponsor.organizze]
      active = false
      site = "https://www.organizze.com.br/?utm_source=tableless&utm_medium=logo&utm_campaign=patrocinio&utm_content=Tableless"
      name = "organizze"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 2