backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://productoversee.com
display_url: https://productoversee.com
locale: 'pt'

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Todos os Post" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
  - name: "posts-diegoeis"
    label: "Posts do Diego Eis"
    folder: "content/posts"
    filter: {field: "authors", value: "Diego Eis"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
  - name: "posts-pablo"
    label: "Posts do Pablo"
    folder: "content/posts"
    filter: {field: "authors", value: "Pablo Silva"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
  - name: "posts-ericka"
    label: "Posts da Ericka"
    folder: "content/posts"
    filter: {field: "authors", value: "Ericka Padilha"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
  - name: "posts-balbino"
    label: "Posts do Lucas"
    folder: "content/posts"
    filter: {field: "authors", value: "Lucas Balbino"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
  - name: "posts-doria"
    label: "Posts do Tiago Doria"
    folder: "content/posts"
    filter: {field: "authors", value: "Tiago Doria"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
  - name: "posts-newton"
    label: "Posts do Newton"
    folder: "content/posts"
    filter: {field: "authors", value: "Newton Calegari"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
  - name: "posts-quintino"
    label: "Posts do Pedro Quintino"
    folder: "content/posts"
    filter: {field: "authors", value: "Pedro Quintino"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
  - name: "categ-opiniao"
    label: "Categoria - Opinião"
    folder: "content/posts"
    filter: {field: "categories", value: "Opinião"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
  - name: "categ-tatico"
    label: "Categoria - Tático"
    folder: "content/posts"
    filter: {field: "categories", value: "Tático"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
  - name: "categ-estrategia"
    label: "Categoria - Estratégia"
    folder: "content/posts"
    filter: {field: "categories", value: "Estratégia"}
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "excerpt", widget: "string"}
      - {label: "Autor", name: "authors", widget: "string"}
      - {label: "Data (aaaa-mm-dd", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Data de publicação (data futura)", name: "publishDate", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Imagem destaque", name: "image", widget: "string"}
      - {label: "Categoria", name: "categories", widget: "list", default: ["Opinião, Estratégia, Tático, Design, Dados & Indicadores"], allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["negócio, mercado, carreira, discovery, ferramenta, agile, desenvolvimento, tecnologia, OKR, métricas"], allow_add: true}
      - {label: "Seu texto", name: "body", widget: "markdown"}
